print("Content-Type: text/html\r\n\r\n")
print("<html>")
print("<head><title>Hello CGI</title></head>")
print("<body>")
print("<h1>Hello from Python CGI!</h1>")
print("<p>This is a basic CGI script working correctly!</p>")
print("</body>")
print("</html>")